### ISSUE TITLE
Update location of BrainHack Marseille

### ISSUE THREAD

**Issue by davidmeunier79** [brainhackorg/global2023#25]
Hi there, 

This year the BrainHack Marseille location has changed, it should read : ""Salle Pouillon, Saiint Charles campus" and the link on OpenStreetMap should be https://www.openstreetmap.org/#map=18/43.30557/5.37775"

Let me know if thats enough information to make the modification

Many thanks

**Comment by crnolan** [comment]
Hi David, can you confirm that this is now correct?

**Comment by davidmeunier79** [comment]
Hi @crnolan. Many thanks for taking care of that. I just see a typo : Saiint -> Saint. Also, is it possible to update our logo with the new one (attached). 
![brainhack2023](https://github.com/brainhackorg/global2023/assets/7290245/888b7f07-6365-4ac4-98c4-b6f831bf23e1)

**Comment by crnolan** [comment]
Hi @davidmeunier79, this should all be fixed now.

**Comment by davidmeunier79** [comment]
yes it is good now , Many thanks @crnolan
