### ISSUE TITLE
Add brainhack Toronto

### ISSUE THREAD

**Issue by Remi-Gau** [brainhackorg/global2023#38]
<google-sheets-html-origin><style type="text/css"></style>

10/24/2023 6:33:21 | Ju-Chi.Yu@camh.ca | 2023 | Dec 14-15 | Brainhack Toronto | Hybrid (in-person and stream of tutorials and projects) | Erin Dickie | Centre for Addiction and Mental Health | Erin.Dickie@camh.ca | @ErinWDickie | Yes | Ju-Chi Yu | Centre for Addiction and Mental Health | Ju-Chi.Yu@camh.ca | @juchiyu | Yes | Toronto | Canada | Krembil Centre for Neuroinformatics, CAMH | 50 | 12 | Yes | https://mattermost.brainhack.org/brainhack/channels/brainhack-toronto | @BrainHackTO | https://brainhackto.github.io/global-toronto-12-2023/ | https://github.com/brainhackto/global-toronto-12-2023 | Yes | N/A | N/A | N/A | No | Panel discussion | Skating | Yes, the main organizers of the event have read the Code of Conduct and we confirm we will abide by it. | N/A |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by juchiyu** [comment]
Hi, could you correct the address for Brainhack Toronto for us? It's not pinned at a different Krembil Centre (sorry, this is confusing). Our address is "250 College St., Toronto, Ontario, M5T 1R8" for The Krembil Centre for Neuroinformatics (12th floor).

**Comment by Remi-Gau** [comment]
Would this one be better?

https://maps.app.goo.gl/J2cjaxuyajCEoAnr5

lat: 43.65931007053005
lon: -79.39946103953687

**Comment by juchiyu** [comment]
Ooh that’s very close, but we still need to go slightly south. Could we use this one?
https://maps.app.goo.gl/mpVLp6azDy34Yr8f7?g_st=ic

**Comment by Remi-Gau** [comment]
okidoki: pushing the change

**Comment by Remi-Gau** [comment]
let me know if it looks better now

**Comment by juchiyu** [comment]
This is perfect! Thank you so much :)
