### ISSUE TITLE
update google form

### ISSUE THREAD

**Issue by Remi-Gau** [brainhackorg/global2023#5]

**Comment by kel-github** [comment]
Link is here: https://docs.google.com/forms/d/e/1FAIpQLSetq7mHJ35__3oppEKzx3YgK6NIyTZnQcISNneFt3PTxOJ4JQ/viewform?usp=sharing

**Comment by crnolan** [comment]
Or short link is https://forms.gle/seQ2ituWQy6SJtoo6
