### ISSUE TITLE
Add BHG Boston

### ISSUE THREAD

**Issue by Remi-Gau** [brainhackorg/global2023#68]
<google-sheets-html-origin><style type="text/css"></style>
11/22/2023 3:33:49 | ayendiki@mgh.harvard.edu | 2023 | December 11-13, 2023 | Brainhack Boston | Hybrid (in-person and stream of tutorials and projects) | Anastasia Yendiki | Massachusetts General Hospital / Harvard Medical School | ayendiki@mgh.harvard.edu | @nastasiayendiki | Yes | Kabilar Gunalan | Massachusetts Institute of Technology | kabi@mit.edu |   | Yes | Boston, MA | USA | Massachusetts Institute of Technology | 20 | 2 | No | https://mattermost.brainhack.org/brainhack/channels/bhg23-boston | N/A | https://brainhack-boston.github.io/ | N/A | Yes | Multimodal imaging of fiber tracts | N/A | N/A | Yes | N/A | N/A | Yes, the main organizers of the event have read the Code of Conduct and we confirm we will abide by it. | No |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by kabilar** [comment]
Thank you, @Remi-Gau @likeajumprope.  (cc @ayendiki)
