### ISSUE TITLE
Add BHG physiopy

### ISSUE THREAD

**Issue by Remi-Gau** [brainhackorg/global2023#69]
<google-sheets-html-origin><style type="text/css"></style>
11/22/2023 4:12:03 | mary.miedema@mail.mcgill.ca | 2023 | December 4-5 | Brainhack Physiopy | Online only | Mary Miedema | McGill University, Physiopy | mary.miedema@mail.mcgill.ca |   | Yes | Stefano Moia | Maastricht University, Physiopy | physiopy.community@gmail.com |   | Yes | Montreal | Canada | Physiopy | 15 | 3 | No | https://mattermost.brainhack.org/brainhack/channels/physiopy | N/A | https://physiopy.github.io/brainhack-physiopy-2023/ | https://github.com/physiopy/ | Yes | Physiology | N/A | Possibly an informal one during our second day, based on participant interest. | Not sure yet! | N/A | N/A | Yes, the main organizers of the event have read the Code of Conduct and we confirm we will abide by it. | No |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by likeajumprope** [comment]
@likeajumprope
